### ISSUE TITLE
Modbus-Proxy with 2 Slave

### ISSUE THREAD

**Issue by jove01** [Akulatraxas/ha-modbusproxy#16]
Hello
I have 2 Slave
(Homeassistant		192.168.178.56)
Solvis WP		192.168.178.67
Sungrow WR		192.168.178.84

Both connected to tcp-port 502.

Both works in HA, but the connection is sometime a day broken.

First: What is the way to define 2 upstreamhost (so another user told)?

Second, i have general Problems to connect the slave to modbus proxy. What is the way  (best in steps) for existing modbus-connection, that it works?

Thanks

**Comment by ChristophCaina** [comment]
Hi,
it appears, that the Modbus-Proxy itself can handle multiple devices / upstream hosts - but the Addon itself might not due to the UI design.

```
devices:
- modbus:
    url: plc1.acme.org:502
  listen:
    bind: 0:9000
- modbus:
    url: plc2.acme.org:502
  listen:
    bind: 0:9001
 ```
 
Maybe, it would be possible to implement this at least for the YAML configuration to allow additional devices to be configured?
I am not sure, if this is really required within the UI settings - since most users would 'probably' use only one upstream host.
