### ISSUE TITLE
Implementierung, RS485 via Adapter (Modbus RTU)

### ISSUE THREAD

**Issue by aerucu** [Akulatraxas/ha-modbusproxy#28]
Ist es möglich in den Modbus Proxy einen RS485 via Adapter (Modbus RTU) zu implementieren?

Mein Wechselrrichter hat einen RS485 Adapter und keine Nettzwerkanbindung. 

Ich wünsche mir folgende Eingabemöglichkeiten. Evtl. mehrfacheingaben möglich?
```
modbusproxy:
    port: 502
    device: /dev/ttyUSB0
    baudrate: 9600
    comset: "8N1"
```
